### ISSUE TITLE
Criar RestController de Cliente e Serviço para listagem de um cliente

### ISSUE THREAD

**Issue by mafesoares** [mafesoares/helpr#1]
- [ ] Criar controlador Rest;
- [ ] Criar serviço de Cliente;
- [ ] Criar métodos para endpoint de RestController;
- [ ] Vincular o repositórios de Cliente;
- [ ] Executar endpoint no Postman.

**Comment by soulcode-acad** [comment]
Oba Fernanda olha tudo certinho código limpo e bem feito deu para acompanhar faltou uns detalhes tipo organizar as entregas e cartões com etiquetas para facilitar o corretor e uma ou outra linha adicional que poderia confundir futuras implantações.

![image](https://user-images.githubusercontent.com/100297907/172921797-be0dda91-2c73-46e5-99ee-145c285623be.png)
